In [2]:
#%pip install numpy
#%pip install pandas
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\Shree\\OneDrive\\Desktop\\Advanced_Multi_Source_Project\\Online_Books _Price & Rating_Analysis\\Book_data1.csv")
df

,Unnamed: 0,title,price,rating,instock,category
0,0,A Light in the Attic,Â£51.77,Three,In stock,Poetry
1,1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction
2,2,Soumission,Â£50.10,One,In stock,Fiction
3,3,Sharp Objects,Â£47.82,Four,In stock,Mystery
4,4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History
...,...,...,...,...,...,...
575,575,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock,Music
576,576,Olio,Â£23.88,One,In stock,Poetry
577,577,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock,Science Fiction
578,578,Libertarianism for Beginners,Â£51.33,Two,In stock,Politics
579,579,It's Only the Himalayas,Â£45.17,Two,In stock,Travel

In [4]:
df.head()
df.info()
df.shape
df.describe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 580 entries, 0 to 579
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  580 non-null    int64
 1   title       580 non-null    object
 2   price       580 non-null    object
 3   rating      580 non-null    object
 4   instock     580 non-null    object
 5   category    580 non-null    object
dtypes: int64(1), object(5)
memory usage: 27.3+ KB

<bound method NDFrame.describe of      Unnamed: 0                                              title    price  \
0             0                               A Light in the Attic  Â£51.77
1             1                                 Tipping the Velvet  Â£53.74
2             2                                         Soumission  Â£50.10
3             3                                      Sharp Objects  Â£47.82
4             4              Sapiens: A Brief History of Humankind  Â£54.23
..          ...                                                ...      ...
575         575  Our Band Could Be Your Life: Scenes from the A...  Â£57.25
576         576                                               Olio  Â£23.88
577         577  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59
578         578                       Libertarianism for Beginners  Â£51.33
579         579                            It's Only the Himalayas  Â£45.17

    rating   instock            category
0    Three  In stock              Poetry
1      One  In stock  Historical Fiction
2      One  In stock             Fiction
3     Four  In stock             Mystery
4     Five  In stock             History
..     ...       ...                 ...
575  Three  In stock               Music
576    One  In stock              Poetry
577    One  In stock     Science Fiction
578    Two  In stock            Politics
579    Two  In stock              Travel

[580 rows x 6 columns]>

In [5]:
df.replace({"N/A":np.nan})

,Unnamed: 0,title,price,rating,instock,category
0,0,A Light in the Attic,Â£51.77,Three,In stock,Poetry
1,1,Tipping the Velvet,Â£53.74,One,In stock,Historical Fiction
2,2,Soumission,Â£50.10,One,In stock,Fiction
3,3,Sharp Objects,Â£47.82,Four,In stock,Mystery
4,4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,History
...,...,...,...,...,...,...
575,575,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock,Music
576,576,Olio,Â£23.88,One,In stock,Poetry
577,577,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock,Science Fiction
578,578,Libertarianism for Beginners,Â£51.33,Two,In stock,Politics
579,579,It's Only the Himalayas,Â£45.17,Two,In stock,Travel

In [6]:
df.isnull().sum()

Unnamed: 0    0
title         0
price         0
rating        0
instock       0
category      0
dtype: int64

In [7]:
# clean the price column
df["price"] = (
    df["price"]
    .astype(str)
    .str.replace("Â", "", regex=False)
    .str.replace("£", "", regex=False)
    .astype(float)
)

In [8]:
print(df['price'].head())

0    51.77
1    53.74
2    50.10
3    47.82
4    54.23
Name: price, dtype: float64

In [9]:
df

,Unnamed: 0,title,price,rating,instock,category
0,0,A Light in the Attic,51.77,Three,In stock,Poetry
1,1,Tipping the Velvet,53.74,One,In stock,Historical Fiction
2,2,Soumission,50.10,One,In stock,Fiction
3,3,Sharp Objects,47.82,Four,In stock,Mystery
4,4,Sapiens: A Brief History of Humankind,54.23,Five,In stock,History
...,...,...,...,...,...,...
575,575,Our Band Could Be Your Life: Scenes from the A...,57.25,Three,In stock,Music
576,576,Olio,23.88,One,In stock,Poetry
577,577,Mesaerion: The Best Science Fiction Stories 18...,37.59,One,In stock,Science Fiction
578,578,Libertarianism for Beginners,51.33,Two,In stock,Politics
579,579,It's Only the Himalayas,45.17,Two,In stock,Travel

In [10]:
# All column names in Title Case

df.rename(columns={"title":"Title",
                   "price":"Price",
                   "rating":"Rating",
                   "instock":"In_stock",
                   "category":"Category",
                   },inplace = True)

In [11]:
df

,Unnamed: 0,Title,Price,Rating,In_stock,Category
0,0,A Light in the Attic,51.77,Three,In stock,Poetry
1,1,Tipping the Velvet,53.74,One,In stock,Historical Fiction
2,2,Soumission,50.10,One,In stock,Fiction
3,3,Sharp Objects,47.82,Four,In stock,Mystery
4,4,Sapiens: A Brief History of Humankind,54.23,Five,In stock,History
...,...,...,...,...,...,...
575,575,Our Band Could Be Your Life: Scenes from the A...,57.25,Three,In stock,Music
576,576,Olio,23.88,One,In stock,Poetry
577,577,Mesaerion: The Best Science Fiction Stories 18...,37.59,One,In stock,Science Fiction
578,578,Libertarianism for Beginners,51.33,Two,In stock,Politics
579,579,It's Only the Himalayas,45.17,Two,In stock,Travel

In [12]:
rating_tag = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["Rating"] = df["Rating"].map(rating_tag)

In [13]:
rating_tag

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}

In [14]:
df

,Unnamed: 0,Title,Price,Rating,In_stock,Category
0,0,A Light in the Attic,51.77,3,In stock,Poetry
1,1,Tipping the Velvet,53.74,1,In stock,Historical Fiction
2,2,Soumission,50.10,1,In stock,Fiction
3,3,Sharp Objects,47.82,4,In stock,Mystery
4,4,Sapiens: A Brief History of Humankind,54.23,5,In stock,History
...,...,...,...,...,...,...
575,575,Our Band Could Be Your Life: Scenes from the A...,57.25,3,In stock,Music
576,576,Olio,23.88,1,In stock,Poetry
577,577,Mesaerion: The Best Science Fiction Stories 18...,37.59,1,In stock,Science Fiction
578,578,Libertarianism for Beginners,51.33,2,In stock,Politics
579,579,It's Only the Himalayas,45.17,2,In stock,Travel

In [15]:
# clean the column availability
df["In_stock"] = df["In_stock"].str.strip()

In [16]:
# clean the column category
df["Category"] = df["Category"].str.strip()

In [17]:
df["Category"].value_counts()

Category
Poetry                116
Default                87
Young Adult            58
Music                  58
Historical Fiction     29
Fiction                29
Mystery                29
History                29
Business               29
Sequential Art         29
Science Fiction        29
Politics               29
Travel                 29
Name: count, dtype: int64

In [18]:
# cleaning the title columns
df["Title"] = df["Title"].str.strip()

In [19]:
df

,Unnamed: 0,Title,Price,Rating,In_stock,Category
0,0,A Light in the Attic,51.77,3,In stock,Poetry
1,1,Tipping the Velvet,53.74,1,In stock,Historical Fiction
2,2,Soumission,50.10,1,In stock,Fiction
3,3,Sharp Objects,47.82,4,In stock,Mystery
4,4,Sapiens: A Brief History of Humankind,54.23,5,In stock,History
...,...,...,...,...,...,...
575,575,Our Band Could Be Your Life: Scenes from the A...,57.25,3,In stock,Music
576,576,Olio,23.88,1,In stock,Poetry
577,577,Mesaerion: The Best Science Fiction Stories 18...,37.59,1,In stock,Science Fiction
578,578,Libertarianism for Beginners,51.33,2,In stock,Politics
579,579,It's Only the Himalayas,45.17,2,In stock,Travel

In [20]:
#check the data types

df.dtypes

Unnamed: 0      int64
Title          object
Price         float64
Rating          int64
In_stock       object
Category       object
dtype: object

In [21]:
# save the cleaned dataset 

df.to_csv("Book_cleaned_dataset1.csv",
          index = False)
print("Cleaned dataset saved sucessfully!")

Cleaned dataset saved sucessfully!